#include <math.h>

#include "Matrix/Matrix_3x3.h"
#include "Steinhart_Hart_Coefficients.h"


/// Calculate the coefficients based on three sets of temperature and resistance.
/// Use Cramer's Rule to solve the three linear equations.
/// The three pairs should be the lowest temperature you need to read,
/// the highest temperature you need to read, and a temperature in the middle.
/// \param	r1	the resistance in ohms
/// \param	t1	the temperature in Kelvin
/// \returns	the set of coefficients generated by the given temperatures and resistances
struct Steinhart_Hart_Coefficients Get_Coefficients(
		const float r1, const float t1, 
		const float r2, const float t2, 
		const float r3, const float t3)
{
	struct Steinhart_Hart_Coefficients coefficients;

	float ln_r1 = log(r1);
	float ln_r2 = log(r2);
	float ln_r3 = log(r3);

	float ln_r1_cubed = ln_r1 * ln_r1 * ln_r1;
	float ln_r2_cubed = ln_r2 * ln_r2 * ln_r2;
	float ln_r3_cubed = ln_r3 * ln_r3 * ln_r3;

	struct Matrix_3x3 matrix;

	Matrix_3x3_Init(&matrix, 
		1, ln_r1, ln_r1_cubed, 
		1, ln_r2, ln_r2_cubed, 
		1, ln_r3, ln_r3_cubed);

	float denominator = Matrix_3x3_Determinant(&matrix);

	Matrix_3x3_Init(&matrix, 
		1.0f / t1, ln_r1, ln_r1_cubed, 
		1.0f / t2, ln_r2, ln_r2_cubed, 
		1.0f / t3, ln_r3, ln_r3_cubed);

	coefficients.a = Matrix_3x3_Determinant(&matrix) / denominator;

	Matrix_3x3_Init(&matrix, 
		1, 1.0f / t1, ln_r1_cubed, 
		1, 1.0f / t2, ln_r2_cubed, 
		1, 1.0f / t3, ln_r3_cubed);

	coefficients.b = Matrix_3x3_Determinant(&matrix) / denominator;

	Matrix_3x3_Init(&matrix, 
		1, ln_r1, 1.0f / t1, 
		1, ln_r2, 1.0f / t2, 
		1, ln_r3, 1.0f / t3);

	coefficients.c = Matrix_3x3_Determinant(&matrix) / denominator;

	return coefficients;
}
